### ISSUE TITLE
[thevoid] signal handling

### ISSUE THREAD

**Issue by torkve** [reverbrain/swarm#26]
Currently thevoid installs its own set of signal handlers ignoring all the previous ones. Since it also ignores --daemonize cmdline option (as well as corresponding config section) it seems to be completely unusable as something embedded — one just cannot start thevoid server along with some other main application, the only way to reliably install own signal handlers (server even has no status variable/method) is to install them inside the application::initialize.

**Comment by bioothod** [comment]
@shindo Danil, please take a look

**Comment by shindo** [comment]
Yep, we've seen and thought about this problem.

I agree that thevoid should not install its own signal handlers, or it should provide convenient method to do this.
After all, it should be user's decision to install signal handlers or not.

**Comment by bioothod** [comment]
Do you plan to change anything?

**Comment by shindo** [comment]
Yes, I think that it's ok to completely remove signal handling mechanics from thevoid.

If I got it right this mechanics was introduced to support handling of multiple servers within single application which is rare.

So, the issue will be solved in v0.7.4.0.

**Comment by bioothod** [comment]
Having multiple servers in one application is very useful thing - this is so far the only way to deal with security/authentication issues. This should not be harmed.

**Comment by shindo** [comment]
Not sure if multiple separate servers within single application is the best solution.
Some kind of smart requests handling (e.g., distinguished by endpoints) will do the thing.
By now thevoid supports initialization of server from configuration file, thus, user should provide multiple configuration files to enable multiple servers.

Removing signal handling will not harm the ability to support multiple servers. User will be completely responsible for handling signals (and stopping their servers on some signal).

**Comment by bioothod** [comment]
So far there is no smart request handling, but we somehow have to prevent some users from running some handlers, the simplest (and quite good in my opinion) solution is to split handlers into separate groups running on different ports - thus different servers

**Comment by shindo** [comment]
I think this issue can be closed as #40 solves the problem.

One just should not use `ioremap::thevoid::run_server()` function to start their server.
Instead one can create server with `ioremap::thevoid::create_server()` and run it with `base_server::run()` method.
This way no signals will be handled by thevoid, and one can register their handlers with `signal()` or `sigaction()`.

Or one can use new thevoid's signal handling mechanics described in the pull request.

**Comment by shindo** [comment]
Fell free to reopen the issue, if the problem persists.
