### ISSUE TITLE
Packages naming scheme

### ISSUE THREAD

**Issue by shindo** [reverbrain/swarm#28]
This pull request is aimed to continue discussion of the issue #25 of unversioned -dev packages.

I suggest to name each -dev package after SONAME number (libthevoid\<SONAME\>-dev, etc.).

This scheme has already been discussed (and it looks as preferred one):
- https://people.debian.org/~adeodato/tmp/2006-03-16/library-transitions.txt
- http://www.netfort.gr.jp/~dancer/column/libpkg-guide/libpkg-guide.html#id291895

This naming scheme allows to explicitly express with which API of the library you want to build. And there will be no need to use version ranges (>= 0.1, << 0.2).

Thus, there will be multiple -dev packages, but only one of them should be installed at a time (because all of them provide symlink to versioned .so library). To solve this problem virtual packages can be used, e.g. each -dev package will provide and conflict with the same virtual package (common for the library):

Package: libthevoid3-dev
Provides: libthevoid-dev
Conflicts: libthevoid-dev

Name of the virtual package can be chosen that user will not want to try to build with it (because it's pointless to build with any API of the library).

Downside of the proposed solution is complicated update of the package. If you will try to install libthevoid4-dev with libthevoid3-dev already installed it will fail. Thus, you should remove libthevoid3-dev before installation of libthevoid4-dev.

This scheme can be used for all common libraries (e.g., thevoid, blackhole, handystats).
What about Elliptics and Cocaine?

Invited speakers:
@shaitan 
@3Hren 
@iderikon 
@ijon
@noxiouz
@bioothod 
@tigro 
@izhidkov
@toshic

**Comment by bioothod** [comment]
What will happen when we want to update package from libX2-dev to libX3-dev, while the latter one conflicts with the former? Will it ever allow this update?

**Comment by shindo** [comment]
Both packages conflict and provide the same virtual package.

If libx2-dev of version 1.0.0 is installed and you want to update to version 1.1.0 everything will be fine.
If libx2-dev is installed and you want to update to libx3-dev apt will fail (because of conflict). In this case user should uninstall libx2-dev and after that install libx3-dev.

This looks bad, but let's think about environment where -dev packages are to be installed:
- developer's host -- looks fine to manually resolve such problems
- build farm (pbuilder's chroot image) -- here no libx*-dev packages are installed by default, thus, no conflicts

We can use "Replaces:" relationship with the base virtual package:
Package: libthevoid3-dev
Provides: libthevoid-dev
Conflicts: libthevoid-dev
Replaces: libthevoid-dev

With "Replaces" if you try to install libx3-dev while libx2-dev is installed, apt will remove libx2-dev and install libx3-dev automatically (if you pass "--yes" option, or apt will ask you for permission to do so).

**Comment by shindo** [comment]
It looks like there's no need to specify "Replaces". 

With

Package: libthevoid3-dev
Provides: libthevoid-dev
Conflicts: libthevoid-dev

the following works:
- installing libx3-dev when libx2-dev is installed automatically removes libx2-dev
- installing libx2-dev when libx3-dev is installed automatically removes libx3-dev

Let libA-dev depends on libx2-dev and libB-dev depends on libx3-dev. The following works:
- installing libA-dev when libx3-dev/libB-dev are installed automatically removes libx3-dev/libB-dev, installs libx2-dev
- installing libx2-dev when libx3-dev/libB-dev are installed automatically removes libx3-dev/libB-dev

Let libC-dev depends on libA-dev and libB-dev.
- installing libC-dev will fail due to unmet dependencies

**Comment by bioothod** [comment]
What is the status of this issue?

**Comment by shindo** [comment]
I'll go with the described versioning/naming scheme.
Hope our common libraries will do the same.
